version: "3.8"

services:
    guitar-tools:
      build: 
        context: .
        dockerfile: DockerFile
      ports:
        - "3000:3000"
      volumes:
        - ../:/app
      tty: true
      networks:
        - piers_dev_network
networks:
  piers_dev_network:
    external: true